name: venkatesh
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.5.0
  onesignal_flutter: ^5.3.4
  google_fonts: ^6.3.0
  page_transition: ^2.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  toastification: ^3.0.3
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  shimmer: ^3.0.0
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  custom_refresh_indicator: ^4.0.1
  flutter_svg: ^2.2.0
  pinput: ^5.0.1
  package_info_plus: ^8.3.1
  camera: ^0.11.2
  webview_flutter: ^4.13.0
  fluttertoast: ^8.2.12
  share_plus: ^11.1.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/lotties/
    - assets/svgs/

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix:
